name: Cleanup PR deploy

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Remove PR folder
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          FOLDER="pr-$PR_NUMBER"

          cd gh-pages
          if [ -d "$FOLDER" ]; then
            rm -rf "$FOLDER"
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Remove preview for PR #$PR_NUMBER"
            git push origin gh-pages
          else
            echo "Folder $FOLDER not found"
          fi
